MDScreen:
    size: 500,500

    MDBoxLayout:
        pos_hint:{"center_x":0.5, "center_y":0.5}
        size_hint:1,1
        valign:"top"
        md_bg_color: "FFF888"
        orientation: "vertical"

        MDLabel:
            text: "Zelan"
            halign: "center"
            font_size: "60pt"

        MDChip:
            text: "Dark Mode"
            pos_hint: {"center_x":0.07, "center_y":0.5}
            on_press:


